# Generated by Django 2.1.7 on 2019-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='building_number',
        ),
        migrations.AddField(
            model_name='place',
            name='building_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
