# Generated by Django 2.1.7 on 2019-02-17 16:43

from django.db import migrations


PLACES = [
    {
        "buildingUnit": "500",
        "buildingName": "Watermans House",
        "streetNumber": "21",
        "streetName": "New Village Agenue",
        "town": "London",
        "postcode": "E140GL"
    },
    {
        "buildingUnit": "4th Floor",
        "buildingName": None,
        "streetNumber": "9-10",
        "streetName": "Charterhouse Buildings",
        "town": "London",
        "postcode": "EC1M7AN"
    },
    {
        "buildingUnit": "Unit G.06",
        "buildingName": "Clerkenwell Workshops",
        "streetNumber": "27-31",
        "streetName": "Clerkenwell Close",
        "town": "London",
        "postcode": "EC1R0AT"
    }
]


def create_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')

    for place in PLACES:
        Place.objects.create(
            building_unit=place['buildingUnit'],
            building_name=place['buildingName'],
            street_number=place['streetNumber'],
            town=place['town'],
            postcode=place['postcode'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20190217_1641'),
    ]

    operations = [
        migrations.RunPython(create_places),
    ]
